/**
  * main.cpp
  * Entry point for the application, generated by Qt Designer.
  */

/**
  * Multilife
  * A Multi-species variant of Conway's Game of Life
  * 
  * Copyright (C) 2009 Joel Murphy, Ba Nguyen
  * All rights reserved
  * Licensed under the GNU Public License, v2. Full text of license can be found
  * in gpl2.txt.
  */

#include <qapplication.h>
#include "formmain.h"

int main( int argc, char ** argv )
{
    QApplication a( argc, argv );
    formMain w;
    w.show();
    a.connect( &a, SIGNAL( lastWindowClosed() ), &a, SLOT( quit() ) );
    return a.exec();
}
